name: Update EPG

on:
  schedule:
    # Run every day at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-epg:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install requests pytz
    
    - name: Generate EPG XML
      run: |
        python generate-epg.py
    
    - name: Commit and push if changed
      run: |
        git config --global user.name 'EPG Bot'
        git config --global user.email 'bot@github.com'
        git add epg.xml
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update EPG - $(date)" && git push)